const images = {//{
    //"aspirations": {
    "Bodybuilder": {
        "source": "Sims images/Aspiration_TS4_Bodybuilder.png",
        "text": "This Sim wants to work out and become as strong as they can be!"
    },
    "Painter Extraordinaire": { 
        "source": "Sims images/Aspiration_TS4_Painter_Extraordinaire.png", "text": "This Sim wants his/her life to be all about art and painting!" },
    "Musical Genius": { 
        "source": "Sims images/Aspiration_TS4_Musical_Genius.png", "text": "This sim wants to become an expert musician and songwriter." },
    "Bestselling Author": { 
        "source": "Sims images/Aspiration_TS4_Bestselling_Author.png", "text": "This sim wants to write books and become a famous author." },
    "Public Enemy": { 
        "source": "Sims images/Aspiration_TS4_Public_Enemy.png", "text": "This sim wants to make enemies and be a famous criminal!" },
    "Chief of Mischief": { 
        "source": "Sims images/Aspiration_TS4_Chief_of_Mischief.png", "text": "This sim is all about pranks and mayhem!" },
    "Villainous Valentine": { 
        "source": "Sims images/Aspiration_TS4_Villainous_Valentine.png", "text": "This Sim wants to destroy the love lives of all Sims, including their own!" },
    "Successful Lineage": { 
        "source": "Sims images/Aspiration_TS4_Successful_Lineage.png", "text": "This sim wants to have a family that succeeds in life." },
    "Big Happy Family": { 
        "source": "Sims images/Aspiration_TS4_Big_Happy_Family.png", "text": "This sim wants to build a large, loving household." },
    "Master Chef": { 
        "source": "Sims images/Aspiration_TS4_Master_Chef.png", "text": "This sim wants to master the culinary arts!" },
    "Master Mixologist": { 
        "source": "Sims images/Aspiration_TS4_Master_Mixologist.png", "text": "This sim wants to know everything there is to know about mixology!”" },
    "Fabulously Wealthy": { 
        "source": "Sims images/Aspiration_TS4_Fabulously_Wealthy.png", "text": "This sim wants to get rich and have a successful career!" },
    "Mansion Baron": { 
        "source": "Sims images/Aspiration_TS4_Mansion_Baron.png", "text": "This sim is all about owning the biggest, fanciest home." },
    "Renaissance Sim": { 
        "source": "Sims images/Aspiration_TS4_Renaissance_Sim.png", "text": "This sim wants to be good at many things at once!" },
    "Nerd Brain": { 
        "source": "Sims images/Aspiration_TS4_Nerd_Brain.png", "text": "This sim wants to be both book smart and handy!" },
    "Computer Whiz": { 
        "source": "Sims images/Aspiration_TS4_Computer_Whiz.png", "text": "This sim wants to know everything about computers, from playing games to careers!" },
    "Serial Romantic": { 
        "source": "Sims images/Aspiration_TS4_Serial_Romantic.png", "text": "This sim wants to play the field and go on dates with all sorts of interesting people." },
    "Soulmate": { "source": "Sims images/Aspiration_TS4_Soulmate.png", "text": "This sim wants to find and live a rewarding life with The One" },
    "Freelance Botanist": { "source": "Sims images/Aspiration_TS4_Freelance_Botanist.png", "text": "This sim wants to grow plants and become an expert gardener." },
    "The Curator": { "source": "Sims images/Aspiration_TS4_The_Curator.png", "text": "This sim wants to collect everything the world has to offer." },
    "Angling Ace": { "source": "Sims images/Aspiration_TS4_Angling_Ace.png", "text": "This sim wants to know everything about fishing." },
    "Joke Star": { "source": "Sims images/Aspiration_TS4_Joke_Star.png", "text": "This sim wants to tell jokes and become a famous comedian" },
    "Party Animal": { "source": "Sims images/Aspiration_TS4_Party_Animal.png", "text": "This sim wants to throw and attend amazing parties." },
    "Friend of The World": { "source": "Sims images/Aspiration_TS4_Friend_of_the_World.png", "text": "This sim wants to make and keep as many friends as they can." },
    "Neighborhood Confidante": { "source": "Sims images/Aspiration_TS4_Neighborhood_Confidante.png", "text": "This Sim wants to provide all manner of advice, to be a positive influence in the lives of their neighbors." },
    "Leader of The Pack": { "source": "Sims images/Aspiration_TS4_Leader_of_the_Pack.png", "text": "This sim wants to be the leader of the best club in town" },
    "City Native": { "source": "Sims images/Aspiration_TS4_City_Native.png", "text": "This sim is all about the city life." },
    "Friend of Animals": { "source": "Sims images/Aspiration_TS4_Friend_of_the_Animals.png", "text": "This sim wants to be friends with the animals." },
    "World-Famous Celebrity": { "source": "Sims images/Aspiration_TS4_World-Famous_Celebrity.png", "text": "This sim wants to be illustriously famous." },
    "Master Actor": { "source": "Sims images/Aspiration_TS4_Master_Actor.png", "text": "This sim wants to hone their craft and become an acclaimed actor." },
    "Beach Life": { "source": "Sims images/Aspiration_TS4_Beach_Life.png", "text": "This sim wants to take it slow and enjoy beach life." },
    "Academic": { "source": "Sims images/Aspiration_TS4_Academic.png", "text": "The sim wantss to attend university and got a job, but most importantly — learn!" },
    "Eco Innovator": { "source": "Sims images/Aspiration_TS4_Eco_Innovator.png", "text": "This sim wants to build a better, greener community." },
    "Master Maker": { "source": "Sims images/Aspiration_TS4_Master_Maker.png", "text": "This sim wants to become an expert at fabrication." },
    "Extreme Sports Enthusiast": { "source": "Sims images/Aspiration_TS4_Extreme_Sports_Enthusiast.png", "text": "This Sim wants to explore Mt. Komorebi's wilderness and participate in extreme snow sports." },
    "Mt.Komorebi Sightseer": { "source": "Sims images/Aspiration_TS4_Mt._Komorebi_Sightseer.png", "text": "This Sim wants to explore Mt. Komorebi's culture and experience everything it has to offer." },
    "Country Caretaker": { "source": "Sims images/Aspiration_TS4_Country_Caretaker.png", "text": "Country Caretakers want to tend the countryside and befriend all animals and critters!" },
    
    "Outdoor Enthusiast": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Inner Peace": { "source": "Sims images/Aspiration_TS4_Inner_Peace.png", "text": "" },
    "Self-Care": { "source": "Sims images/Aspiration_TS4_Self-Care_Specialist.png", "text": "" },
    "Zen Guru": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Vampire Family": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Master Vampire": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Good Vampire": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Super Parent": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Jungle Explorer": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Archaeology Scholar": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "StrangerVille Mystery": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Pureveyor Of Potions": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Spellcraft & Sorcery": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Lone Wolf": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Emissary Of The Collective": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Wildfang Renegade": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Cure Seeker": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Lord/Lady Of The Knits": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Perfectly Pristine": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Fabulously Filthy": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    

    
    //},
    //"traits": {
    "Active": { "source": "Sims images/Trait_TS4_Active.png", "text": "These Sims tend to be Energized, can Pump Up other Sims, and may become upset if they don't exercise for a period of time." },
    "Cheerful": { "source": "Sims images/Trait_TS4_Cheerful.png", "text": "These Sims tend to be Happier than other Sims." },
    "Creative": { "source": "Sims images/Trait_TS4_Creative.png", "text": "These Sims tend to be Inspired, can Share Creative Ideas with other Sims, and may become upset if they're not creative for a period of time." },
    "Genius": { "source": "Sims images/Trait_TS4_Genius.png", "text": "These Sims tend to be Focused, can Share Ideas with other Sims, and may become upset if they haven't improved their Mental Skills for some time." },
    "Gloomy": { "source": "Sims images/Trait_TS4_Gloomy.png", "text": "These Sims tend to be Sad, can Share Melancholy Thoughts to other Sims, and while sad, gain a boost to their Creative Skill." },
    "Goofball": { "source": "Sims images/Trait_TS4_Goofball.png", "text": "These Sims tend to be Playful." },
    "Hot-Headed": { "source": "Sims images/Trait_TS4_Hot-Headed.png", "text": "These Sims tend to be Angry, can Rile up other Sims, and become Angry when targeted with Mischief." },
    "Romantic": { "source": "Sims images/Trait_TS4_Romantic.png", "text": "These Sims tend to be Flirty and may become Sad if they don't have any Romantic social interactions for a period of time." },
    "Self-assured": { "source": "Sims images/Trait_TS4_Self-Assured.png", "text": "These Sims tend to be Confident." },
    "Art Lover": { "source": "Sims images/Trait_TS4_Art_Lover.png", "text": "These Sims gain powerful Moodlets from Viewing works of art and can Admire Art and Discuss Art in unique ways." },
    "Bookworm": { "source": "Sims images/Trait_TS4_Bookworm.png", "text": "These Sims gain powerful Moodlets from reading Books and can Analyze Books and Discuss Books in unique ways." },
    "Foodie": { "source": "Sims images/Trait_TS4_Foodie.png", "text": "These Sims become Happy and have Fun when eating good food, become Uncomfortable when eating bad food, and can Watch Cooking Shows for ideas" },
    "Geek": { "source": "Sims images/Trait_TS4_Geek.png", "text": "These Sims become Happy when Reading Sci-Fi or Playing Video Games, may become Tense if they haven't played much, are better at finding Collectibles, and can Discuss Geek Things with other Geek Sims." },
    "Music Lover": { "source": "Sims images/Trait_TS4_Music_Lover.png", "text": "These Sims gain powerful Moodlets and boost their Fun Need when Listening to Music and become Happy when playing instruments." },
    "Perfectionist": { "source": "Sims images/Trait_TS4_Perfectionist.png", "text": "These Sims take longer to craft items but tend to make them higher quality, gain powerful Moodlets after crafting a high quality item, and gain negative Moodlets after crafting a low quality item." },
    "Ambitious": { "source": "Sims images/Trait_TS4_Ambitious.png", "text": "These Sims gain powerful Moodlets from career success, gain negative Moodlets from career failure, and may become Tense if not promoted." },
    "Childish": { "source": "Sims images/Trait_TS4_Childish.png", "text": "These Sims gain powerful Moodlets from watching the Kids Network, become Playful when playing with Children, and become Happy when playing with Children's toys." },
    "Clumsy": { "source": "Sims images/Trait_TS4_Clumsy.png", "text": "These Sims tend to fail more often at physical activities and tend to laugh at failure instead of becoming upset." },
    "Erratic": { "source": "Sims images/Trait_TS4_Erratic.png", "text": "These Sims can Talk to themselves and have unpredictable Emotions." },
    "Glutton": { "source": "Sims images/Trait_TS4_Glutton.png", "text": "These Sims have a greater negative reaction to Hunger, always enjoy eating, no matter the quality of the food, and will eat Spoiled Food." },
    "Kleptomaniac": { "source": "Sims images/Trait_TS4_Kleptomaniac.png", "text": "These Sims don't mind 'borrowing' things from others with a simple swipe, but will get Tense when they have not swiped anything in a while." },
    "Lazy": { "source": "Sims images/Trait_TS4_Lazy.png", "text": "These Sims gain powerful Moodlets from Watching TV or Napping as well as from Comfortable furniture, become Fatigued more quickly from exercise, and grow Tense when performing household chores." },
    "Loves Outdoors": { "source": "Sims images/Trait_TS4_Loves_Outdoors.png", "text": "These Sims can Enthuse about Nature to other Sims and become Happy when Outdoors." },
    "Materialistic": { "source": "Sims images/Trait_TS4_Materialistic.png", "text": "These Sims can Admire and Brag about Possessions and become Sad when they haven't purchased a new item for a period of time." },
    "Neat": { "source": "Sims images/Trait_TS4_Neat.png", "text": "These Sims become Happy and have Fun when performing household chores, can have a Cleaning Frenzy, and become really Uncomfortable in dirty surroundings." },
    "Slob": { "source": "Sims images/Trait_TS4_Slob.png", "text": "These Sims are not affected by dirty surroundings, make household items dirtier faster, and can Rummage for Food in garbage." },
    "Snob": { "source": "Sims images/Trait_TS4_Snob.png", "text": "These Sims can Critique Work on low quality items, are bored by 'low brow' television, and gain Confidence around other Snob Sims." },
    "Vegetarian": { "source": "Sims images/Trait_TS4_Vegetarian.png", "text": "These Sims will actively avoid eating foods that contain meat products and can become sick if they eat such foods." },
    "Bro": { "source": "Sims images/Trait_TS4_Bro.png", "text": "These Sims can Bro Hug other Bros, gain Confidence around other Bros, and become Energized from Watching Sports." },
    "Evil": { "source": "Sims images/Trait_TS4_Evil.png", "text": "These Sims become Happy around Sims with negative Moodlets, can Laugh Maniacally and Discuss Evil Plans, and become Angry when interacting with Good Sims." },
    "Family-oriented": { "source": "Sims images/Trait_TS4_Family-Oriented.png", "text": "These Sims become Happy around family members, become Sad if they don't interact with family for a period of time, and can Boast about Family." },
    "Noncommittal": { "source": "Sims images/Trait_TS4_Noncommittal.png", "text": "These Sims become Tense after a while in the same job or relationship, become Happy when they Quit a Job or Break Off a relationship, take longer to Propose, and can Discuss their Fear of Commitment." },
    "Good": { "source": "Sims images/Trait_TS4_Good.png", "text": "These Sims become Happy around Sims with positive Moodlets, can Donate to Charity, become Sad with interacting with Evil Sims, and can Discuss World Peace." },
    "Hates Children": { "source": "Sims images/Trait_TS4_Hates_Children.png", "text": "These Sims become Angry around Children, become Tense after Try for a Baby, and can be Mean to Children." },
    "Jealous": { "source": "Sims images/Trait_TS4_Jealous.png", "text": "These Sims get Jealous more easily than other Sims. They gain a boost of Confidence from being around their significant other, but get Tense if they haven't seen them recently." },
    "Loner": { "source": "Sims images/Trait_TS4_Loner.png", "text": "These Sims become Happy when alone, do not receive negative Moodlets when their Social Need is low, become Tense around strangers, and become Embarrassed more often by social rejection." },
    "Loyal": { "source": "Sims images/Trait_TS4_Loyal.png", "text": "Loyal sims value their relationships and fully commit to them. whether they are friendship, romance or even work! They avoid lying and cheating because their loved ones' trust is very important to them." },
    "Mean": { "source": "Sims images/Trait_TS4_Mean.png", "text": "These Sims become Happy when being Mean or Mischievous to other Sims and become Confident after winning a fight." },
    "Outgoing": { "source": "Sims images/Trait_TS4_Outgoing.png", "text": "These Sims gain powerful Moodlets from Friendly socialization, have their Social need decay quickly, and gain more negative Moodlets when their Social need is low." },
    "Insider": { "source": "Sims images/Trait_TS4_Insider.png", "text": "These Sims love being in Clubs, and tend to be happiest when surrounded by their friends." },
    "Dance Machine": { "source": "Sims images/Trait_TS4_Dance_Machine.png", "text": "These Sims can't wait to get down, boogie, and party all night! When at venues like Bars, Nightclubs, and Lounges, these Sims can get a burst of energy with the Party Time interaction." },
    "Unflirty": { "source": "Sims images/Trait_TS4_Unflirty.png", "text": "These Sims get Tense around Flirty Sims and seldom get Flirty themselves. It's difficult for them to be Romantic in public." },
    "Cat Lover": { "source": "Sims images/Trait_TS4_Cat_Lover.png", "text": "These Sims tend to make cats their companions, preferring the company of cats to other Sims." },
    "Dog Lover": { "source": "Sims images/Trait_TS4_Dog_Lover.png", "text": "These Sims love to be near dogs. They will gain relationships faster with dogs and socialize with dogs more than the average Sim." },
    "Self-absorbed": { "source": "Sims images/Trait_TS4_Self-Absorbed.png", "text": "These Sims are all about themselves! They can Fish for Compliments, are more excited when receiving a present, and may become tense when they haven't gotten enough attention. The celebrity spotlight is something they generally relish. After all, everyone else should love them as much as they do themselves, right?" },
    "Child of the Islands": { "source": "Sims images/Trait_TS4_Child_of_the_Islands.png", "text": "These Sims experience a spiritual connection to islands of Sulani. Honor the islands by partaking in their culture, summon powerful elementals and reap the rewards of their blessings—or the consequences of their disfavor." },
    "Child of the Ocean": { "source": "Sims images/Trait_TS4_Child_of_the_Ocean.png", "text": "Answer the call of the ocean! Sims with this trait will prefer water related activities and feel closer to denizens of the sea." },
    "Freegan": { "source": "Sims images/Trait_TS4_Freegan.png", "text": "These Sims reject consumerism and prefer to reduce wasteful spending by any means. They enjoy finding re-used or thrown away goods and foods. In fact, they have the best luck at finding the highest-quality treasures in Dumpsters! They may become tense or uncomfortable if they spend too much time earning or spending Simoleons." },
    "Green Fiend": { "source": "Sims images/Trait_TS4_Green_Fiend.png", "text": "These Sims are happiest when living on a green street and will continuously work towards making their environment more eco-friendly." },
    "Recycle Disciple": { "source": "Sims images/Trait_TS4_Recycle_Disciple.png", "text": "These Sims are rabid recyclers that benefit from recycling and rummaging for bits and pieces, but should they go too long without indulging in their hobby..." },
    "Maker": { "source": "Sims images/Trait_TS4_Maker.png", "text": "These Sims become happy when making things. They become sad when it's been too long since completing a project on a Fabricator, Candlemaking Station, Juice Fizzer, or Woodworking Table. They do not receive negative effects from crafting or repair failures." },
    "Adventurous": { "source": "Sims images/Trait_TS4_Adventurous.png", "text": "These Sims seek out new and unique experiences." },
    "Proper": { "source": "Sims images/Trait_TS4_Proper.png", "text": "These Sims tend to disapprove of other Sims' improper behavior such as Mean or Mischievous socials, but find themselves happier in Formal Outfits and have a much easier time with Friendly and Romantic socials." },
    "Animal Enthusiast": { "source": "Sims images/Trait_TS4_Animal_Enthusiast.png", "text": "These Sims are obsessed with animals, and will seek their company often. They will have an easier time caring for animals and getting closer to them." },
    "Lactose Intolerant": { "source": "Sims images/Trait_TS4_Lactose_Intolerant.png", "text": "These Sims will become sick if they eat dairy, but will feel great if they have avoided it for a while." },
    
    "Squeamish": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "High Maintenance": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Paranoid": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    
    //},
    //"careers": {
    'Astronaut': { "source": "Sims images/TS4_Career_Astronaut.png", "alt": "" },
    'Athlete': { "source": "Sims images/TS4_Career_Athlete.png", "alt": "" },
    'Business': { "source": "Sims images/TS4_Career_Business.png", "alt": "" },
    'Criminal': { "source": "Sims images/TS4_Career_Criminal.png", "alt": "" },
    'Culinary': { "source": "Sims images/TS4_Career_Culinary.png", "alt": "" },
    'Entertainer': { "source": "Sims images/TS4_Career_Entertainer.png", "alt": "" },
    'Freelance': { "source": "Sims images/TS4_Career_Freelancer.png", "alt": "" },
    'Painter': { "source": "Sims images/TS4_Career_Painter.png", "alt": "" },
    'Secret Agent': { "source": "Sims images/TS4_Career_Secret_Agent.png", "alt": "" },
    'Style Influencer': { "source": "Sims images/TS4_Career_Style_Influencer.png", "alt": "" },
    'Writer': { "source": "Sims images/TS4_Career_Writer.png", "alt": "" },
    "Doctor": { "source": "Sims images/TS4_Career_Doctor.png", "alt": "" },
    "Scientist": { "source": "Sims images/TS4_Career_Scientist.png", "alt": "" },
    "Detective": { "source": "Sims images/TS4_Career_Detective.png", "alt": "" },
    
    "Critic": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Politician": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Social Media": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Actor/Actress": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Conservationist": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Education": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Engineer": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Law": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Civil Designer": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Salaryperson": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Military": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },

    //},
    //"likes": {
    'Comedy': { "source": "Sims images/Skill_TS4_Comedy.png", "alt": "" },
    'Cooking': { "source": "Sims images/Skill_TS4_Cooking.png", "alt": "" },
    'Fishing': { "source": "Sims images/Skill_TS4_Fishing.png", "alt": "" },
    'Fitness': { "source": "Sims images/Skill_TS4_Fitness.png", "alt": "" },
    'Gardening': { "source": "Sims images/Skill_TS4_Gardening.png", "alt": "" },
    'Guitar': { "source": "Sims images/Skill_TS4_Guitar.png", "alt": "" },
    'Handiness': { "source": "Sims images/TS4_Like_Handiness.png", "alt": "" },
    'Mischief': { "source": "Sims images/Skill_TS4_Mischief.png", "alt": "" },
    'Mixology': { "source": "Sims images/TS4_Like_Mixology.png", "alt": "" },
    'Painting': { "source": "Sims images/painting.PNG", "alt": "" },
    'Piano': { "source": "Sims images/TS4_Like_Piano.png", "alt": "" },
    'Programming': { "source": "Sims images/Skill_TS4_Programming.png", "alt": "" },
    'Rocket Science': { "source": "Sims images/TS4_Like_Rocket_Science.png", "alt": "" },
    'Video Gaming': { "source": "Sims images/Skill_TS4_Video_Gaming.png", "alt": "" },
    'Violin': { "source": "Sims images/Skill_TS4_Violin.png", "alt": "" },
    'Writing': { "source": "Sims images/writing.PNG", "alt": "" },
    'Alternative Music': { "source": "Sims images/TS4_Like_Alternative_Music.png", "alt": "" },
    'Blues Music': { "source": "Sims images/TS4_Like_Blues_Music.png", "alt": "" },
    'Classical Music': { "source": "Sims images/TS4_Like_Classical_Music.png", "alt": "" },
    'Electronica Music': { "source": "Sims images/TS4_Like_Electronica_Music.png", "alt": "" },
    'Hip Hop Music': { "source": "Sims images/TS4_Like_Hip_Hop_Music.png", "alt": "" },
    'Kids Music': { "source": "Sims images/TS4_Like_Kids_Music.png", "alt": "" },
    'Lullabies Music': { "source": "Sims images/TS4_Like_Lullabies_Music.png", "alt": "" },
    'Pop Music': { "source": "Sims images/TS4_Like_Pop_Music.png", "alt": "" },
    'Retro Music': { "source": "Sims images/TS4_Like_Retro_Music.png", "alt": "" },
    'Romance Music': { "source": "Sims images/TS4_Like_Romance_Music.png", "alt": "" },
    'S-Pop Music': { "source": "Sims images/TS4_Like_S-Pop_Music.png", "alt": "" },
    'Spooky Music': { "source": "Sims images/TS4_Like_Spooky_Music.png", "alt": "" },
    'World Music': { "source": "Sims images/TS4_Like_World_Music.png", "alt": "" },
    'Winter Holiday Music': { "source": "Sims images/TS4_Like_Winter_Holiday_Music.png", "alt": "" },
    "Easy Listening Music": { "source": "Sims images/TS4_Like_Easy_Listening_Music.png", "alt": "" },
    "Baking": { "source": "Sims images/TS4_Like_Baking.png", "alt": "" },
    "Photography": { "source": "Sims images/Skill_TS4_Photography.png", "alt": "" },
    "Easy Listening Music": { "source": "Sims images/TS4_Like_Easy_Listening_Music.png", "alt": "" },
    "Photography": { "source": "Sims images/Skill_TS4_Photography.png", "alt": "" },
    "DJ Mixing": { "source": "Sims images/Skill_TS4_DJ_Mixing.png", "alt": "" },
    "Dancing": { "source": "Sims images/dancing.PNG", "alt": "" },
    "DJ Booth Music": { "source": "Sims images/TS4_Like_DJ_Booth_Music.png", "alt": "" },
    "Singing": { "source": "Sims images/TS4_Like_Singing.png", "alt": "" },
    "Singer-Songwriter Music": { "source": "Sims images/TS4_Like_Singer-Songwriter_Music.png", "alt": "" },
    "Acting": { "source": "Sims images/Skill_TS4_Acting.png", "alt": "" },
    "Media Production": { "source": "Sims images/Skill_TS4_Media_production.png", "alt": "" },
    "Island Radio Music": { "source": "Sims images/TS4_Like_Island_Music.png", "alt": "" },
    "Research & Debate": { "source": "Sims images/Skill_TS4_Research_&_Debate.png", "alt": "" },
    "Robotics": { "source": "Sims images/Skill_TS4_Robotics.png", "alt": "" },
    "Rock Climbing": { "source": "Sims images/Skill_TS4_Rock_Climbing.png", "alt": "" },
    "Skiing": { "source": "Sims images/TS4_Like_Skiing.png", "alt": "" },
    "Snowboarding": { "source": "Sims images/TS4_Like_Snowboarding.png", "alt": "" },
    "Japanese Folk Music": { "source": "Sims images/TS4_Like_Japanese_Folk_Music.png", "alt": "" },
    "Cross-stitch": { "source": "Sims images/TS4_Like_Cross-stitch.png", "alt": "" },
    "Cottagecore Music": { "source": "Sims images/TS4_Like_Cottagecore_Music.png", "alt": "" },
    
    "Wellness": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "New Age Music": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Pipe Organ": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Latin Pop Music": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Latin Music": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Strange Tunes Music": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Metal Music": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },

    //},
    //"occults": {
    "Default": { "source": "Sims images/defaultPlumbob.png", "alt": "" },
    "Alien": { "source": "Sims images/Trait_TS4_Alien.png", "alt": "" },
    "Mermaid": { "source": "Sims images/TS4_Mermaid_Icon.png", "alt": "" },
    "Vampire": { "source": "Sims images/TS4_Vampire_Icon.png", "alt": "" },
    "Spellcaster": { "source": "Sims images/TS4_Spellcaster_Icon.png", "alt": "" },
    //},
    //"worlds":{
    "Willow Creek": { "source": "Sims images/Willow_Creek_ingame_icon.png", "alt": "" },
    "Oasis Springs": { "source": "Sims images/Oasis_Springs_ingame_icon.png", "alt": "" },
    "Newcrest": { "source": "Sims images/Newcrest_ingame_icon.png", "alt": "" },
    "Windenburg": { "source": "Sims images/Windenburg.png", "alt": "" },
    "San Myshuno": { "source": "Sims images/SanMyshunoWorldIcon.png", "alt": "" },
    "Brindleton Bay": { "source": "Sims images/brindletonbay.PNG", "alt": "" },
    "Del Sol Valley": { "source": "Sims images/delsolvalley.PNG", "alt": "" },
    "Sulani": { "source": "Sims images/sulani.PNG", "alt": "" },
    "Britechester": { "source": "Sims images/BritechesterLogo.png", "alt": "" },
    "Evergreen Harbor": { "source": "Sims images/Evergreen_Harbor_Icon.png", "alt": "" },
    "Mt. Komorebi": { "source": "Sims images/Mt._Komorebi_Icon.png", "alt": "" },
    "Henford-on-Bagley": { "source": "Sims images/HenfordLogo.png", "alt": "" },
    
    "Forgotten Hollow": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "StrangerVille": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Glimmerbrook": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    "Moonwood Mill": { "source": "Sims images/Aspiration_TS4_Outdoor_Enthusiast.png", "text": "" },
    //},
    //}
}
const firstname = ["Alison", "Kaylynn", "Kameron", "Laci", "Jaqueline", "Emmalee", "Paige", "Neal", "Justina", "Garrett", "Caitlin", "Janelle", "Conor", "Cheryl", "Janine", "Cannon", "Devan", "Kiera", "Hunter", "Damaris", "Tyrese", "Juana", "Kristopher", "Tristan", "Johnpaul", "Kimberly", "Mikael", "Leila", "Parker", "Darryl", "Trystan", "Clint", "Malka", "Leah", "Kendal", "Sadie", "Mercy", "Jocelyne", "Ashton", "Jerod", "Cori", "Alonzo", "Isabelle", "Rhianna", "Camille", "Kameryn", "Ezequiel", "Breonna", "Ciarra", "Simon", "Raheem", "Taylor", "Jaylynn", "Jackson", "Fredy", "Nehemiah", "Salena", "Cameryn", "Cyrus", "Mindy", "Devlin", "Jaylin", "Mariela", "Aiden", "Kolby", "Jocelynn", "Rory", "Kennedy", "Denis", "Marian", "Conner", "Kyle", "Abigayle", "Blanca", "Carleigh", "Theresa", "Cornelius", "Tomas", "Austyn", "Marcello", "Junior", "Semaj", "Davis", "Simran", "Sebastien", "Alysia", "Racheal", "Camden", "Jimmie", "Morgan", "Jadah", "Shayla", "Keyara", "Maren", "Corey", "Jonathan", "Harvey", "Alana", "Marcellus", "Darrell", "Abram", "Yasmine", "Levi", "Gunner", "Arielle", "Danyelle", "Amy", "Coral", "Marina", "Arianna", "Sana", "Helen", "Clayton", "Gisel", "Yisroel", "Susan", "Tonya", "Leighton", "Leonard", "Kaden", "Calvin", "Kierra", "Mohammed", "Tess", "Jeremy", "Adelaide", "Kristine", "Kristi", "Joana", "Kaleigh", "Silas", "Briar", "Shyanne", "Alexandra", "Katelyn", "Peter", "Vance", "Pauline", "Gino", "Alani", "Zaira", "Carson", "Taylar", "Samuel", "Dominic", "Hollie", "Rodney", "Joy", "Nathanial", "Yazmine", "Tabitha", "Hali", "Dewayne", "Peyton", "Willie", "Lynn", "Frederick", "Jaiden", "Roman", "Elsa", "Lloyd", "Meg", "Nico", "Keila", "Marcel", "Kelsi", "Marlen", "Alivia", "Noor", "Irvin", "Teagan", "Jade", "Hillary", "Cain", "Thaddeus", "Riana", "Jarett", "Davon", "Monique", "Felipe", "Eleanor", "Jill", "Dario", "Claudio", "Davin", "Cedrick", "Quentin", "Rafael", "Liam", "Xavier", "Samaria", "Janette", "Kristofer", "Jalon", "Barbara", "Clarence", "Kendrick", "Henry", "Siobhan", "Cale", "Leona", "Cristina", "Colby", "Keith", "Hadley", "Dasia", "Anyssa", "Brieanna", "Laisha", "Malaysia", "Ricky", "Beau", "Gilberto", "Dean", "Dustyn", "Leo", "Alyson", "Alexander", "Evan", "Anthony", "Aaliyah", "Ajay", "Mara", "Myranda", "Harold", "Keon", "Yahaira", "Kurt", "Keelan", "Ellis", "Alyssia", "River", "Johnna", "Julius", "Sarahi", "Tony", "Fernando", "Uriel", "Keshaun", "Shaina", "Lester", "Pablo", "Raelyn", "Brady", "Dajuan", "Lewis", "Rayna", "Diane", "Jevon", "Ross"]
const lastname = ["Mattingly", "Armenta", "Ballard", "Kilgore", "Kemper", "Moore", "Scherer", "Vickers", "Park", "Meyers", "Wu", "Gray", "Guillen", "Carter", "Crowe", "Nadeau", "Fair", "Hoy", "Herndon", "Navarro", "McGregor", "Holley", "Chaffin", "Reddick", "Patrick", "Fine", "Cranford", "Burt", "Bruce", "Mabry", "Swartz", "Dodd", "Holloway", "Naranjo", "Tsai", "Hanlon", "McManus", "Taylor", "Leary", "Schindler", "Kent", "Vega", "Cochrane", "Acevedo", "Richardson", "Sandlin", "Platt", "Brumfield", "Mitchell", "Broyles", "Waddell", "Elmore", "Bautista", "Leggett", "Hahn", "Ontiveros", "Correa", "Atwell", "Boss", "Delgadillo", "Maldonado", "Tipton", "Shockley", "Tuttle", "Lai", "Rosales", "Hickman", "Bean", "Wilkerson", "Nevarez", "Cintron", "Owens", "Gilchrist", "Barclay", "Ricci", "Cote", "Huffman", "Hargis", "Wong", "Rubio", "Do", "Devine", "Brubaker", "Colburn", "Fay", "Delong", "Sommers", "Morrow", "Medlin", "Lanier", "Mathew", "Taggart", "Mcnutt", "Tang", "Shuler", "Counts", "Stallings", "Massey", "Arce", "Register", "Hairston", "Espino", "Helm", "Kramer", "Self", "Kern", "Merchant", "Renner", "Goodrich", "Blaylock", "Menendez", "Sutter", "Bowen", "Spicer", "Kahn", "Brandenburg", "Swafford", "Valdez", "Huff", "Tompkins", "Fabian", "Samuel", "McNair", "Robb", "Landis", "Torrez", "Parra", "Alves", "Hannon", "Humphrey", "Baron", "Blanchard", "Thigpen", "Buckley", "Baxter", "Gentry", "Shackelford", "Haddad", "Parson", "Blue", "Rose", "Rivera", "Clemons", "Duong", "Traylor", "Park", "Enriquez", "Saavedra", "Oglesby", "Mattson", "Shanahan", "McMillan", "Padilla", "Breeden", "Chung", "Starkey", "Warner", "Hay", "Samson", "Egan", "Rourke", "Simons", "Pickett", "Swan", "Kearney", "Valentin", "Carden", "Paredes", "McLain", "Amaral", "Clements", "Jacobsen", "Kauffman", "Hayward", "Calderon", "Ferguson", "Guinn", "Willis", "Luke", "Rincon", "Alarcon", "Johnson", "Gold", "Gonzalez", "Kee", "Conroy", "Goodwin", "Chastain", "Newell", "Hite", "Xiong", "Clough", "Peebles", "Aquino", "Gilliland", "Dupont", "Tejeda", "Hickey", "Fong", "Girard", "Ng", "Leonard", "Adler", "Herbert", "Zeller", "Kemp", "Keeler", "Hundley", "Lowe", "Easter", "Bohannon", "Merritt", "Burkhart", "Montgomery", "Monson", "Seymour", "Shea", "Hatcher", "Leal", "Liles", "Arellano", "Patel", "Murphy", "Wilhelm", "Whitlock", "Drew", "Castillo", "Ouellette", "Derrick", "Wylie", "France", "Huang", "Haskell", "Burton", "Kirk", "Tafoya", "McCloud", "Kelso", "Godinez", "Nettles", "Rodriquez", "Richey", "Pearce", "Aparicio", "Bachman", "Fahey", "Allan", "Corral", "Dutton", "Murdock"]