const images = [
    {
        "aspirations": {
            "Bodybuilder":{"source":"Sims images/Aspiration_TS4_Bodybuilder.png","text":""},
            "Painter Extraordinaire":{"source":"Sims images/Aspiration_TS4_Painter_Extraordinaire.png","text":""},
            "Musical Genius":{"source":"Sims images/Aspiration_TS4_Musical_Genius.png","text":""},
            "Bestselling Author":{"source":"Sims images/Aspiration_TS4_Bestselling_Author.png","text":""},
            "Public Enemy":{"source":"Sims images/Aspiration_TS4_Public_Enemy.png","text":""},
            "Chief of Mischief":{"source":"Sims images/Aspiration_TS4_Chief_of_Mischief.png","text":""},
            "Villainous Valentine":{"source":"Sims images/Aspiration_TS4_Villainous_Valentine.png","text":""},
            "Successful Lineage":{"source":"Sims images/Aspiration_TS4_Successful_Lineage.png","text":""},
            "Big Happy Family":{"source":"Sims images/Aspiration_TS4_Big_Happy_Family.png","text":""},
            "Master Chef":{"source":"Sims images/Aspiration_TS4_Master_Chef.png","text":""},
            "Master Mixologist":{"source":"Sims images/Aspiration_TS4_Master_Mixologist.png","text":""},
            "Fabulously Wealthy":{"source":"Sims images/Aspiration_TS4_Fabulously_Wealthy.png","text":""},
            "Mansion Baron":{"source":"Sims images/Aspiration_TS4_Mansion_Baron.png","text":""},
            "Renaissance Sim":{"source":"Sims images/Aspiration_TS4_Renaissance_Sim.png","text":""},
            "Nerd Brain":{"source":"Sims images/Aspiration_TS4_Nerd_Brain.png","text":""},
            "Computer Whiz":{"source":"Sims images/Aspiration_TS4_Computer_Whiz.png","text":""},
            "Serial Romantic":{"source":"Sims images/Aspiration_TS4_Serial_Romantic.png","text":""},
            "Soulmate":{"source":"Sims images/Aspiration_TS4_Soulmate.png","text":""},
            "Freelance Botanist":{"source":"Sims images/Aspiration_TS4_Freelance_Botanist.png","text":""},
            "The Curator":{"source":"Sims images/Aspiration_TS4_The_Curator.png","text":""},
            "Angling Ace":{"source":"Sims images/Aspiration_TS4_Angling_Ace.png","text":""},
            "Joke Star":{"source":"Sims images/Aspiration_TS4_Joke_Star.png","text":""},
            "Party Animal":{"source":"Sims images/Aspiration_TS4_Party_Animal.png","text":""},
            "Friend of The World":{"source":"Sims images/Aspiration_TS4_Friend_of_the_World.png","text":""},
            "Neighborhood Confidante":{"source":"Sims images/Aspiration_TS4_Neighborhood_Confidante.png","text":""},
            "Leader of The Pack":{"source":"Sims images/Aspiration_TS4_Leader_of_the_Pack.png","text":""},
            "City Native":{"source":"Sims images/Aspiration_TS4_City_Native.png","text":""},
            "Friend of Animals":{"source":"Sims images/Aspiration_TS4_Friend_of_the_Animals.png","text":""},
            "World-Famous Celebrity":{"source":"Sims images/Aspiration_TS4_World-Famous_Celebrity.png","text":""},
            "Master Actor":{"source":"Sims images/Aspiration_TS4_Master_Actor.png","text":""},
            "Beach Life":{"source":"Sims images/Aspiration_TS4_Beach_Life.png","text":""},
            "Academic":{"source":"Sims images/Aspiration_TS4_Academic.png","text":""},
            "Eco Innovator":{"source":"Sims images/Aspiration_TS4_Eco_Innovator.png","text":""},
            "Master Maker":{"source":"Sims images/Aspiration_TS4_Master_Maker.png","text":""},
            "Extreme Sports Enthusiast":{"source":"Sims images/Aspiration_TS4_Extreme_Sports_Enthusiast.png","text":""},
            "Mt.Komorebi Sightseer":{"source":"Sims images/Aspiration_TS4_Mt._Komorebi_Sightseer.png","text":""},
            "Country Caretaker":{"source":"Sims images/Aspiration_TS4_Country_Caretaker.png","text":""},
        },
        "traits": {
            "Active":{"source":"Sims images/Trait_TS4_Active.png","alt":"Active"},
            "Cheerful":{"source":"Sims images/Trait_TS4_Cheerful.png","alt":"Cheerful"},
            "Creative":{"source":"Sims images/Trait_TS4_Creative.png","alt":"Creative"},
            "Genius":{"source":"Sims images/Trait_TS4_Genius.png","alt":"Genius"},
            "Gloomy":{"source":"Sims images/Trait_TS4_Gloomy.png","alt":"Gloomy"},
            "Goofball":{"source":"Sims images/Trait_TS4_Goofball.png","alt":"Goofball"},
            "Hot-Headed":{"source":"Sims images/Trait_TS4_Hot-Headed.png","alt":"Hot-Headed"},
            "Romantic":{"source":"Sims images/Trait_TS4_Romantic.png","alt":"Romantic"},
            "Self-assured":{"source":"Sims images/Trait_TS4_Self-Assured.png","alt":""},
            "Art Lover":{"source":"Sims images/Trait_TS4_Art_Lover.png","alt":""},
            "Bookworm":{"source":"Sims images/Trait_TS4_Bookworm.png","alt":""},
            "Foodie":{"source":"Sims images/Trait_TS4_Foodie.png","alt":""},
            "Geek":{"source":"Sims images/Trait_TS4_Geek.png","alt":""},
            "Music Lover":{"source":"Sims images/Trait_TS4_Music_Lover.png","alt":""},
            "Perfectionist":{"source":"Sims images/Trait_TS4_Perfectionist.png","alt":""},
            "Ambitious":{"source":"Sims images/Trait_TS4_Ambitious.png","alt":""},
            "Childish":{"source":"Sims images/Trait_TS4_Childish.png","alt":""},
            "Clumsy":{"source":"Sims images/Trait_TS4_Clumsy.png","alt":""},
            "Erratic":{"source":"Sims images/Trait_TS4_Erratic.png","alt":""},
            "Glutton":{"source":"Sims images/Trait_TS4_Glutton.png","alt":""},
            "Kleptomaniac":{"source":"Sims images/Trait_TS4_Kleptomaniac.png","alt":""},
            "Lazy":{"source":"Sims images/Trait_TS4_Lazy.png","alt":""},
            "Loves Outdoors":{"source":"Sims images/Trait_TS4_Loves_Outdoors.png","alt":""},
            "Materialistic":{"source":"Sims images/Trait_TS4_Materialistic.png","alt":""},
            "Neat":{"source":"Sims images/Trait_TS4_Neat.png","alt":""},
            "Slob":{"source":"Sims images/Trait_TS4_Slob.png","alt":""},
            "Snob":{"source":"Sims images/Trait_TS4_Snob.png","alt":""},
            "Vegetarian":{"source":"Sims images/Trait_TS4_Vegetarian.png","alt":""},
            "Bro":{"source":"Sims images/Trait_TS4_Bro.png","alt":""},
            "Evil":{"source":"Sims images/Trait_TS4_Evil.png","alt":""},
            "Family-oriented":{"source":"Sims images/Trait_TS4_Family-Oriented.png","alt":""},
            "Noncommittal":{"source":"Sims images/Trait_TS4_Noncommittal.png","alt":""},
            "Good":{"source":"Sims images/Trait_TS4_Good.png","alt":""},
            "Hates Children":{"source":"Sims images/Trait_TS4_Hates_Children.png","alt":""},
            "Jealous":{"source":"Sims images/Trait_TS4_Jealous.png","alt":""},
            "Loner":{"source":"Sims images/Trait_TS4_Loner.png","alt":""},
            "Loyal":{"source":"Sims images/Trait_TS4_Loyal.png","alt":""},
            "Mean":{"source":"Sims images/Trait_TS4_Mean.png","alt":""},
            "Outgoing":{"source":"Sims images/Trait_TS4_Outgoing.png","alt":""},
            "Insider":{"source":"Sims images/Trait_TS4_Insider.png","alt":""},
            "Dance Machine":{"source":"Sims images/Trait_TS4_Dance_Machine.png","alt":""},
            "Unflirty":{"source":"Sims images/Trait_TS4_Unflirty.png","alt":""},
            "Cat Lover":{"source":"Sims images/Trait_TS4_Cat_Lover.png","alt":""},
            "Dog Lover":{"source":"Sims images/Trait_TS4_Dog_Lover.png","alt":""},
            "Self-absorbed":{"source":"Sims images/Trait_TS4_Self-Absorbed.png","alt":""},
            "Child of the Islands":{"source":"Sims images/Trait_TS4_Child_of_the_Islands.png","alt":""},
            "Child of the Ocean":{"source":"Sims images/Trait_TS4_Child_of_the_Ocean.png","alt":""},
            "Freegan":{"source":"Sims images/Trait_TS4_Freegan.png","alt":""},
            "Green Fiend":{"source":"Sims images/Trait_TS4_Green_Fiend.png","alt":""},
            "Recycle Disciple":{"source":"Sims images/Trait_TS4_Recycle_Disciple.png","alt":""},
            "Maker":{"source":"Sims images/Trait_TS4_Maker.png","alt":""},
            "Adventurous":{"source":"Sims images/Trait_TS4_Adventurous.png","alt":""},
            "Proper":{"source":"Sims images/Trait_TS4_Proper.png","alt":""},
            "Animal Enthusiast":{"source":"Sims images/Trait_TS4_Animal_Enthusiast.png","alt":""},
            "Lactose Intolerant":{"source":"Sims images/Trait_TS4_Lactose_Intolerant.png","alt":""},
        },
        "careers": {
            'Astronaut':{"source":"Sims images/TS4_Career_Astronaut.png","alt":""},
            'Athlete':{"source":"Sims images/TS4_Career_Athlete.png","alt":""},
            'Business':{"source":"Sims images/TS4_Career_Business.png","alt":""},
            'Criminal':{"source":"Sims images/TS4_Career_Criminal.png","alt":""},
            'Culinary':{"source":"Sims images/TS4_Career_Culinary.png","alt":""},
            'Entertainer':{"source":"Sims images/TS4_Career_Entertainer.png","alt":""},
            'Freelance':{"source":"Sims images/TS4_Career_Freelancer.png","alt":""},
            'Painter':{"source":"Sims images/TS4_Career_Painter.png","alt":""},
            'Secret Agent':{"source":"Sims images/TS4_Career_Secret_Agent.png","alt":""},
            'Style Influencer':{"source":"Sims images/TS4_Career_Style_Influencer.png","alt":""},
            'Writer':{"source":"Sims images/TS4_Career_Writer.png","alt":""},
            "Doctor":{"source":"Sims images/TS4_Career_Doctor.png","alt":""},
            "Scientist":{"source":"Sims images/TS4_Career_Scientist.png","alt":""},
            "Detective":{"source":"Sims images/TS4_Career_Detective.png","alt":""},
        },
        "likes": {
            'Comedy':{"source":"","alt":""},
            'Cooking':{"source":"","alt":""},
            'Fishing':{"source":"","alt":""},
            'Fitness':{"source":"","alt":""},
            'Gardening':{"source":"","alt":""},
            'Guitar':{"source":"","alt":""},
            'Handiness':{"source":"","alt":""},
            'Mischief':{"source":"","alt":""},
            'Mixology':{"source":"","alt":""},
            'Painting':{"source":"","alt":""},
            'Piano':{"source":"","alt":""},
            'Programming':{"source":"","alt":""},
            'Rocket Science':{"source":"","alt":""},
            'Video Gaming':{"source":"","alt":""},
            'Violin':{"source":"","alt":""},
            'Writing':{"source":"","alt":""},
            'Alternative Music':{"source":"","alt":""},
            'Blues Music':{"source":"","alt":""},
            'Classical Music':{"source":"","alt":""},
            'Electronica Music':{"source":"","alt":""},
            'Hip Hop Music':{"source":"","alt":""},
            'Kids Music':{"source":"","alt":""},
            'Lullabies Music':{"source":"","alt":""},
            'Pop Music':{"source":"","alt":""},
            'Retro Music':{"source":"","alt":""},
            'Romance Music':{"source":"","alt":""},
            'S-Pop Music':{"source":"","alt":""},
            'Spooky Music':{"source":"","alt":""},
            'World Music':{"source":"","alt":""},
            'Winter Holiday Music':{"source":"","alt":""},
            "Easy Listening Music":{"source":"","alt":""},
            "Baking":{"source":"","alt":""},
            "Photography":{"source":"","alt":""},
            "Easy Listening Music":{"source":"","alt":""},
            "Baking":{"source":"","alt":""},
            "Photography":{"source":"","alt":""},
            "DJ Mixing":{"source":"","alt":""},
            "Dancing":{"source":"","alt":""},
            "DJ Booth Music":{"source":"","alt":""},
            "Singing":{"source":"","alt":""},
            "Singer-Songwriter Music":{"source":"","alt":""},
            "Acting":{"source":"","alt":""},
            "Media Production":{"source":"","alt":""},
            "Island Radio Music":{"source":"","alt":""},
            "Research & Debate":{"source":"","alt":""},
            "Robotics":{"source":"","alt":""},
            "Rock Climbing":{"source":"","alt":""},
            "Skiing":{"source":"","alt":""},
            "Snowboarding":{"source":"","alt":""},
            "Japanese Folk Music":{"source":"","alt":""},
            "Cross-stitch":{"source":"","alt":""},
            "Cottagecore Music":{"source":"","alt":""},
        },
        "occults": {
            "Default":{"source":"","alt":""},
            "Alien":{"source":"","alt":""},
            "Mermaid":{"source":"","alt":""},
        },
        "worlds":{
            "Willow Creek":{"source":"","alt":""},
            "Oasis Springs":{"source":"","alt":""},
            "Newcrest":{"source":"","alt":""},
            "Windenburg":{"source":"","alt":""},
            "San Myshuno":{"source":"","alt":""},
            "Brindleton Bay":{"source":"","alt":""},
            "Del Sol Valley":{"source":"","alt":""},
            "Sulani":{"source":"","alt":""},
            "Britechester":{"source":"","alt":""},
            "Evergreen Harbor":{"source":"","alt":""},
            "Mt. Komorebi":{"source":"","alt":""},
            "Henford-on-Bagley":{"source":"","alt":""},
        },
    }
]
const firstname = []
const lastname = []